### PR TITLE
Fix EnvironmentOnly test to work on Linux too

### PR DESCRIPTION
**Pull request by mzlarsson**
The test `EnvironmentOnly` seems to be windows-only (fails on back slashes instead of slashes). I split the test into two parts for it to work on linux too and added it to the ci tests to make sure we verify it.

### CODE REVIEW

**Comment by mzlarsson** [comment]
@gjb1002 It looks like the windows build environment for selftest in Github actions has been broken since September last year, have you (or any other of the maintainers) looked into this (as you know of)?

**Comment by gjb1002** [comment]
@behrisch - do you know anything about this, I believe you set up this environment?

**Comment by behrisch** [comment]
This should be more or less a direct copy of the corresponding workflow in the texttest main repo. I will update it

**Comment by mzlarsson** [comment]
Thanks @behrisch :+1:

**Pull request merged**
